/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => OrbitInsightsPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian4 = require("obsidian");

// src/client.ts
var OrbitClient = class {
  constructor(settings) {
    this.settings = settings;
  }
  /**
   * Attempt to read .pkmrag/server_token or .orbit/server_token from active vault filesystem.
   */
  async autoDiscoverVaultToken(app) {
    try {
      for (const tokenPath of [".pkmrag/server_token", ".orbit/server_token"]) {
        const exists = await app.vault.adapter.exists(tokenPath);
        if (exists) {
          const content = await app.vault.adapter.read(tokenPath);
          const trimmed = content.trim();
          if (trimmed.length > 0) {
            this.settings.authToken = trimmed;
            return trimmed;
          }
        }
      }
    } catch (err) {
      console.warn("[PKMRAG] Could not auto-read server_token:", err);
    }
    return null;
  }
  getHeaders() {
    const headers = {
      "Content-Type": "application/json"
    };
    if (this.settings.authToken && this.settings.authToken.trim().length > 0) {
      const tok = this.settings.authToken.trim();
      headers["Authorization"] = `Bearer ${tok}`;
      headers["X-Pkmrag-Token"] = tok;
    }
    return headers;
  }
  /**
   * Health probe verifying Orbit daemon connectivity.
   */
  async checkHealth() {
    const url = `${this.settings.serverUrl.replace(/\/+$/, "")}/health`;
    const res = await fetch(url, { method: "GET" });
    if (!res.ok) {
      throw new Error(`Health check failed with HTTP ${res.status}`);
    }
    return await res.json();
  }
  /**
   * Retrieve graph context (outgoing links, backlinks, tags, AI inferences) for a note.
   */
  async getNoteContext(notePath) {
    const base = this.settings.serverUrl.replace(/\/+$/, "");
    const url = `${base}/api/v1/context?note_path=${encodeURIComponent(notePath)}`;
    const res = await fetch(url, {
      method: "GET",
      headers: this.getHeaders()
    });
    if (res.status === 404) {
      return null;
    }
    if (!res.ok) {
      throw new Error(`Context fetch failed with HTTP ${res.status}`);
    }
    return await res.json();
  }
  /**
   * Retrieve unlinked note candidates with high semantic similarity.
   */
  async getGaps(notePath, threshold, limit) {
    const base = this.settings.serverUrl.replace(/\/+$/, "");
    const thresh = threshold ?? this.settings.similarityThreshold;
    const lim = limit ?? this.settings.maxSuggestions;
    let url = `${base}/api/v1/gaps?threshold=${thresh}&limit=${lim}`;
    if (notePath) {
      url += `&note_path=${encodeURIComponent(notePath)}`;
    }
    const res = await fetch(url, {
      method: "GET",
      headers: this.getHeaders()
    });
    if (!res.ok) {
      throw new Error(`Gaps fetch failed with HTTP ${res.status}`);
    }
    const data = await res.json();
    return data.candidates || [];
  }
  /**
   * Incrementally reindex a single note after edits and evict stale cache.
   */
  async reindexNote(notePath) {
    const base = this.settings.serverUrl.replace(/\/+$/, "");
    const url = `${base}/api/v1/reindex`;
    const res = await fetch(url, {
      method: "POST",
      headers: this.getHeaders(),
      body: JSON.stringify({ note_path: notePath })
    });
    if (!res.ok) {
      throw new Error(`Reindex failed with HTTP ${res.status}`);
    }
    return await res.json();
  }
  /**
   * Delta synchronize all modified or newly created vault notes.
   */
  async syncVault() {
    const base = this.settings.serverUrl.replace(/\/+$/, "");
    const url = `${base}/api/v1/sync`;
    const res = await fetch(url, {
      method: "POST",
      headers: this.getHeaders()
    });
    if (!res.ok) {
      throw new Error(`Vault sync failed with HTTP ${res.status}`);
    }
    const data = await res.json();
    return data.results || [];
  }
  /**
   * Search knowledge base chunks biased by graph proximity to an anchor note.
   */
  async searchVault(query, near, limit) {
    const base = this.settings.serverUrl.replace(/\/+$/, "");
    const url = `${base}/api/v1/search`;
    const payload = {
      query: query.trim(),
      limit: limit || 5
    };
    if (near) {
      payload.near = near;
    }
    const res = await fetch(url, {
      method: "POST",
      headers: this.getHeaders(),
      body: JSON.stringify(payload)
    });
    if (!res.ok) {
      throw new Error(`Search failed with HTTP ${res.status}`);
    }
    const data = await res.json();
    return data.results || [];
  }
  /**
   * Subscribe to live SSE events from Orbit server.
   */
  connectEvents(onEvent) {
    if (typeof EventSource === "undefined") {
      return null;
    }
    try {
      const base = this.settings.serverUrl.replace(/\/+$/, "");
      const tokenParam = this.settings.authToken ? `?token=${encodeURIComponent(this.settings.authToken)}` : "";
      const source = new EventSource(`${base}/api/v1/events${tokenParam}`);
      source.addEventListener("reindex", (e) => {
        try {
          onEvent("reindex", JSON.parse(e.data));
        } catch {
        }
      });
      source.addEventListener("sync", (e) => {
        try {
          onEvent("sync", JSON.parse(e.data));
        } catch {
        }
      });
      return source;
    } catch (err) {
      console.warn("[Orbit] Could not establish EventSource stream:", err);
      return null;
    }
  }
};

// src/extension.ts
var import_state = require("@codemirror/state");
var import_view = require("@codemirror/view");
var OrbitHeadingWidget = class extends import_view.WidgetType {
  constructor(count, hasContradiction, onClick) {
    super();
    this.count = count;
    this.hasContradiction = hasContradiction;
    this.onClick = onClick;
  }
  toDOM() {
    const span = document.createElement("span");
    span.className = `orbit-inline-indicator ${this.hasContradiction ? "orbit-inline-warning" : "orbit-inline-normal"}`;
    span.textContent = this.hasContradiction ? " \u26A0\uFE0F" : " \u{1F517}";
    span.title = `PKMRAG: ${this.count} unlinked connection${this.count > 1 ? "s" : ""}${this.hasContradiction ? " (includes contradiction)" : ""}. Click to open sidebar.`;
    span.onclick = (e) => {
      e.stopPropagation();
      e.preventDefault();
      this.onClick();
    };
    return span;
  }
};
function createOrbitEditorExtension(plugin) {
  return import_view.ViewPlugin.fromClass(
    class {
      decorations;
      constructor(view) {
        this.decorations = this.buildDecorations(view);
      }
      update(update) {
        if (update.docChanged || update.viewportChanged) {
          this.decorations = this.buildDecorations(update.view);
        }
      }
      buildDecorations(view) {
        if (!plugin.settings.showInlineIndicators) {
          return import_view.Decoration.none;
        }
        const activeFile = plugin.app.workspace.getActiveFile();
        if (!activeFile) {
          return import_view.Decoration.none;
        }
        const count = plugin.getActiveGapsCount(activeFile.path);
        const hasContra = plugin.hasActiveContradiction(activeFile.path);
        if (count === 0 && !hasContra) {
          return import_view.Decoration.none;
        }
        const builder = new import_state.RangeSetBuilder();
        let hasDecoratedFirst = false;
        for (const { from, to } of view.visibleRanges) {
          let pos = from;
          while (pos <= to) {
            const line = view.state.doc.lineAt(pos);
            const lineText = line.text;
            if (/^#{1,6}\s+/.test(lineText)) {
              builder.add(
                line.to,
                line.to,
                import_view.Decoration.widget({
                  widget: new OrbitHeadingWidget(count, hasContra, () => {
                    plugin.activateView();
                  }),
                  side: 1
                })
              );
              hasDecoratedFirst = true;
              break;
            }
            pos = line.to + 1;
          }
          if (hasDecoratedFirst) break;
        }
        return builder.finish();
      }
    },
    {
      decorations: (v) => v.decorations
    }
  );
}

// src/settings.ts
var import_obsidian = require("obsidian");
var OrbitSettingTab = class extends import_obsidian.PluginSettingTab {
  plugin;
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "PKMRAG Knowledge Engine Settings" });
    new import_obsidian.Setting(containerEl).setName("Server URL").setDesc("Base address of PKMRAG HTTP/SSE daemon (default: http://127.0.0.1:3747)").addText(
      (text) => text.setPlaceholder("http://127.0.0.1:3747").setValue(this.plugin.settings.serverUrl).onChange(async (val) => {
        this.plugin.settings.serverUrl = val;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Authentication Token").setDesc("Bearer token for server access (auto-detected from .pkmrag/server_token)").addText(
      (text) => text.setPlaceholder("Auto-detected or custom token").setValue(this.plugin.settings.authToken).onChange(async (val) => {
        this.plugin.settings.authToken = val;
        await this.plugin.saveSettings();
      })
    ).addButton(
      (btn) => btn.setButtonText("Auto-Detect").onClick(async () => {
        const tok = await this.plugin.client.autoDiscoverVaultToken(this.app);
        if (tok) {
          new import_obsidian.Notice(`Found server token in vault!`);
          await this.plugin.saveSettings();
          this.display();
        } else {
          new import_obsidian.Notice(`No .pkmrag/server_token file found in vault.`);
        }
      })
    );
    new import_obsidian.Setting(containerEl).setName("Server Status").setDesc("Verify communication with local PKMRAG daemon").addButton(
      (btn) => btn.setButtonText("Test Connection").onClick(async () => {
        btn.setDisabled(true);
        try {
          const health = await this.plugin.client.checkHealth();
          new import_obsidian.Notice(`PKMRAG Connected! Vault: '${health.vault}', Version: v${health.version}`);
        } catch (err) {
          const msg = err instanceof Error ? err.message : String(err);
          new import_obsidian.Notice(`Connection failed: ${msg}`);
        } finally {
          btn.setDisabled(false);
        }
      })
    );
    containerEl.createEl("h3", { text: "Behavior & Thresholds" });
    new import_obsidian.Setting(containerEl).setName("Auto-Sync on Save").setDesc("Incrementally re-index note into LadybugDB & LanceDB after file modifications").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.autoSyncOnSave).onChange(async (val) => {
        this.plugin.settings.autoSyncOnSave = val;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Auto-Refresh on Note Open").setDesc("Automatically refresh sidebar insights when switching active markdown note").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.autoRefreshOnNoteOpen).onChange(async (val) => {
        this.plugin.settings.autoRefreshOnNoteOpen = val;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Similarity Threshold").setDesc("Minimum cosine similarity for unlinked semantic gap recommendations (0.50 - 0.95)").addSlider(
      (slider) => slider.setLimits(0.5, 0.95, 0.05).setValue(this.plugin.settings.similarityThreshold).setDynamicTooltip().onChange(async (val) => {
        this.plugin.settings.similarityThreshold = val;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Max Suggestions").setDesc("Maximum missing link cards displayed per note (1 - 20)").addSlider(
      (slider) => slider.setLimits(1, 20, 1).setValue(this.plugin.settings.maxSuggestions).setDynamicTooltip().onChange(async (val) => {
        this.plugin.settings.maxSuggestions = val;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Show Inline Heading Indicators").setDesc("Display subtle link/contradiction indicators next to Markdown headings in the editor").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.showInlineIndicators).onChange(async (val) => {
        this.plugin.settings.showInlineIndicators = val;
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h3", { text: "Knowledge Governance & Memory" });
    const dismissedCount = Object.keys(this.plugin.settings.dismissedSuggestions || {}).length;
    new import_obsidian.Setting(containerEl).setName("Dismissed Suggestions Memory").setDesc(`${dismissedCount} suggestion${dismissedCount === 1 ? "" : "s"} currently hidden by negative feedback`).addButton(
      (btn) => btn.setButtonText("Reset All Dismissed").onClick(async () => {
        this.plugin.settings.dismissedSuggestions = {};
        await this.plugin.saveSettings();
        new import_obsidian.Notice("Reset all dismissed suggestions.");
        this.display();
      })
    );
  }
};

// src/types.ts
var DEFAULT_SETTINGS = {
  serverUrl: "http://127.0.0.1:3747",
  authToken: "",
  autoSyncOnSave: true,
  autoRefreshOnNoteOpen: true,
  similarityThreshold: 0.75,
  maxSuggestions: 5,
  showInlineIndicators: true,
  dismissedSuggestions: {}
};

// src/view.ts
var import_obsidian3 = require("obsidian");

// src/view_offline.ts
var import_obsidian2 = require("obsidian");
function renderOfflineView(container, plugin, onRetry) {
  const wrapper = container.createDiv({ cls: "orbit-offline-container" });
  const iconEl = wrapper.createDiv({ cls: "orbit-offline-icon" });
  (0, import_obsidian2.setIcon)(iconEl, "pkmrag-ribbon");
  wrapper.createEl("h3", { text: "PKMRAG Daemon Offline", cls: "orbit-offline-title" });
  wrapper.createEl("p", {
    cls: "orbit-offline-desc",
    text: `PKMRAG daemon is not reachable at ${plugin.settings.serverUrl}. Start the daemon to inspect graph insights, missing links, and contradictions:`
  });
  const codeBox = wrapper.createDiv({ cls: "orbit-code-box" });
  const cmd = `uv run pkmrag serve . -t http --port 3747`;
  codeBox.createEl("code", { text: cmd });
  const copyBtn = codeBox.createEl("button", { cls: "orbit-copy-btn", text: "Copy" });
  copyBtn.onclick = () => {
    navigator.clipboard.writeText(cmd);
    new import_obsidian2.Notice("Copied command to clipboard!");
  };
  const btnRow = wrapper.createDiv({ cls: "orbit-offline-actions" });
  const retryBtn = btnRow.createEl("button", {
    cls: "orbit-btn-sm mod-cta",
    text: "Retry Connection"
  });
  retryBtn.onclick = () => {
    retryBtn.setText("Connecting...");
    retryBtn.setAttribute("disabled", "true");
    onRetry();
  };
  const settingsBtn = btnRow.createEl("button", {
    cls: "orbit-btn-sm",
    text: "Settings"
  });
  settingsBtn.onclick = () => {
    plugin.app.setting?.open?.();
    plugin.app.setting?.openTabById?.(plugin.manifest.id);
  };
}

// src/view_search.ts
var ProximitySearchDrawer = class {
  constructor(parentEl, plugin, getCurrentNotePath) {
    this.parentEl = parentEl;
    this.plugin = plugin;
    this.getCurrentNotePath = getCurrentNotePath;
    this.render();
  }
  containerEl;
  resultsEl;
  inputEl;
  searchTimer = null;
  isOpen = false;
  render() {
    this.containerEl = this.parentEl.createDiv({ cls: "orbit-search-container" });
    const toggleRow = this.containerEl.createDiv({ cls: "orbit-search-toggle" });
    const toggleBtn = toggleRow.createEl("button", {
      cls: "orbit-btn-sm orbit-search-btn",
      text: "\u{1F50D} Concept Explorer"
    });
    const searchBox = this.containerEl.createDiv({
      cls: "orbit-search-box orbit-hidden"
    });
    toggleBtn.onclick = () => {
      this.isOpen = !this.isOpen;
      searchBox.toggleClass("orbit-hidden", !this.isOpen);
      if (this.isOpen) {
        this.inputEl.focus();
      } else {
        this.resultsEl.empty();
        this.inputEl.value = "";
      }
    };
    this.inputEl = searchBox.createEl("input", {
      type: "text",
      placeholder: "Search concepts near this note...",
      cls: "orbit-search-input"
    });
    this.inputEl.oninput = () => {
      if (this.searchTimer) window.clearTimeout(this.searchTimer);
      const query = this.inputEl.value.trim();
      if (!query) {
        this.resultsEl.empty();
        return;
      }
      this.searchTimer = window.setTimeout(() => this.executeSearch(query), 350);
    };
    this.resultsEl = searchBox.createDiv({ cls: "orbit-search-results" });
  }
  async executeSearch(query) {
    this.resultsEl.empty();
    const loadingEl = this.resultsEl.createDiv({
      cls: "orbit-empty-state",
      text: "Searching graph..."
    });
    try {
      const near = this.getCurrentNotePath() || void 0;
      const results = await this.plugin.client.searchVault(query, near, 4);
      loadingEl.remove();
      if (results.length === 0) {
        this.resultsEl.createDiv({
          cls: "orbit-empty-state",
          text: `No matching chunks found for "${query}".`
        });
        return;
      }
      for (const res of results) {
        this.renderResultCard(res);
      }
    } catch (err) {
      loadingEl.setText(err instanceof Error ? err.message : String(err));
    }
  }
  renderResultCard(res) {
    const card = this.resultsEl.createDiv({ cls: "orbit-card orbit-search-card" });
    const head = card.createDiv({ cls: "orbit-card-header" });
    const titleEl = head.createEl("a", {
      cls: "orbit-card-target",
      text: res.title || res.path.replace(/\.md$/, "")
    });
    titleEl.onclick = () => this.plugin.app.workspace.openLinkText(res.path, "");
    if (res.heading) {
      head.createSpan({ cls: "orbit-badge", text: `# ${res.heading}` });
    }
    const excerpt = res.content.length > 120 ? res.content.slice(0, 120) + "..." : res.content;
    card.createDiv({ cls: "orbit-card-reason", text: excerpt });
    const actions = card.createDiv({ cls: "orbit-card-actions" });
    const insertBtn = actions.createEl("button", {
      cls: "orbit-btn-sm",
      text: "+ Insert Ref"
    });
    insertBtn.onclick = () => {
      const linkText = res.heading ? `${res.title || res.path.replace(/\.md$/, "")}#${res.heading}` : res.title || res.path.replace(/\.md$/, "");
      this.plugin.insertLink(linkText);
    };
  }
};

// src/view.ts
var VIEW_TYPE_ORBIT_INSIGHTS = "orbit-insights-view";
var OrbitInsightsView = class extends import_obsidian3.ItemView {
  plugin;
  currentNotePath = null;
  context = null;
  gaps = [];
  lastUpdated = null;
  isLoading = false;
  errorMessage = null;
  showDismissed = false;
  constructor(leaf, plugin) {
    super(leaf);
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE_ORBIT_INSIGHTS;
  }
  getDisplayText() {
    return "PKMRAG Insights";
  }
  getIcon() {
    return "pkmrag-ribbon";
  }
  async onOpen() {
    const activeFile = this.app.workspace.getActiveFile();
    if (activeFile && activeFile.extension === "md") {
      await this.loadInsightsForNote(activeFile.path);
    } else {
      this.render();
    }
  }
  async loadInsightsForNote(notePath) {
    this.currentNotePath = notePath;
    this.isLoading = true;
    this.errorMessage = null;
    this.render();
    try {
      const [ctx, gaps] = await Promise.all([
        this.plugin.client.getNoteContext(notePath),
        this.plugin.client.getGaps(notePath)
      ]);
      this.context = ctx;
      this.gaps = gaps;
      this.lastUpdated = /* @__PURE__ */ new Date();
      this.plugin.setActiveInsights(notePath, gaps, ctx?.inferred_relationships || []);
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      this.errorMessage = message;
    } finally {
      this.isLoading = false;
      this.render();
    }
  }
  render() {
    const container = this.containerEl.children[1];
    container.empty();
    container.addClass("orbit-insights-container");
    const headerEl = container.createDiv({ cls: "orbit-header" });
    const topRow = headerEl.createDiv({ cls: "orbit-header-top" });
    const title = this.currentNotePath ? this.currentNotePath.replace(/\.md$/, "") : "No Note Active";
    topRow.createDiv({ cls: "orbit-header-title", text: title });
    const actions = topRow.createDiv({ cls: "orbit-header-actions" });
    const refreshBtn = actions.createEl("button", { cls: "orbit-btn-sm", text: "\u27F3" });
    refreshBtn.onclick = () => {
      if (this.currentNotePath) this.loadInsightsForNote(this.currentNotePath);
    };
    const statusText = this.isLoading ? "Scanning vault..." : this.lastUpdated ? `Updated ${this.lastUpdated.toLocaleTimeString()}` : "Idle";
    headerEl.createDiv({ cls: "orbit-sync-status", text: statusText });
    if (this.errorMessage) {
      renderOfflineView(container, this.plugin, () => {
        if (this.currentNotePath) this.loadInsightsForNote(this.currentNotePath);
      });
      return;
    }
    if (!this.currentNotePath) {
      container.createDiv({
        cls: "orbit-empty-state",
        text: "Open a markdown note to inspect graph context and suggestions."
      });
      return;
    }
    new ProximitySearchDrawer(container, this.plugin, () => this.currentNotePath);
    this.renderGapsSection(container);
    this.renderInferencesSection(container);
    this.renderContextSection(container);
  }
  renderGapsSection(container) {
    const dismissed = this.plugin.settings.dismissedSuggestions || {};
    const visibleGaps = this.gaps.filter(
      (g) => !dismissed[`${g.source_path}::${g.target_path}`]
    );
    const sec = container.createDiv({ cls: "orbit-section" });
    sec.createDiv({
      cls: "orbit-section-header",
      text: `Missing Links (${visibleGaps.length})`
    });
    if (visibleGaps.length === 0) {
      sec.createDiv({ cls: "orbit-empty-state", text: "No unlinked semantic gaps detected." });
    } else {
      for (const gap of visibleGaps) {
        this.renderGapCard(sec, gap);
      }
    }
    this.renderDismissedDrawer(sec);
  }
  renderGapCard(sec, gap) {
    const isTarget = gap.source_path === this.currentNotePath;
    const otherTitle = isTarget ? gap.target_title : gap.source_title;
    const otherPath = isTarget ? gap.target_path : gap.source_path;
    const card = sec.createDiv({ cls: "orbit-card" });
    const cardHead = card.createDiv({ cls: "orbit-card-header" });
    const targetLink = cardHead.createEl("a", {
      cls: "orbit-card-target",
      text: otherTitle || otherPath.replace(/\.md$/, "")
    });
    targetLink.onclick = () => this.app.workspace.openLinkText(otherPath, "");
    const pct = Math.round(gap.similarity * 100);
    cardHead.createSpan({ cls: "orbit-badge", text: `${pct}% similar` });
    card.createDiv({
      cls: "orbit-card-reason",
      text: `Graph distance: ${gap.hops} hops away with high semantic proximity.`
    });
    const actions = card.createDiv({ cls: "orbit-card-actions" });
    const insertBtn = actions.createEl("button", {
      cls: "orbit-btn-sm mod-cta",
      text: "+ Link"
    });
    insertBtn.onclick = () => this.plugin.insertLink(otherTitle || otherPath.replace(/\.md$/, ""));
    const dismissBtn = actions.createEl("button", { cls: "orbit-btn-sm", text: "Dismiss" });
    dismissBtn.onclick = async () => {
      const key = `${gap.source_path}::${gap.target_path}`;
      if (!this.plugin.settings.dismissedSuggestions) {
        this.plugin.settings.dismissedSuggestions = {};
      }
      this.plugin.settings.dismissedSuggestions[key] = {
        sourcePath: gap.source_path,
        targetPath: gap.target_path,
        targetTitle: otherTitle,
        dismissedAt: Date.now()
      };
      await this.plugin.saveSettings();
      this.render();
    };
  }
  renderDismissedDrawer(sec) {
    const dismissed = this.plugin.settings.dismissedSuggestions || {};
    const noteDismissed = Object.entries(dismissed).filter(
      ([_, item]) => this.currentNotePath && (item.sourcePath === this.currentNotePath || item.targetPath === this.currentNotePath)
    );
    if (noteDismissed.length === 0) return;
    const drawer = sec.createDiv({ cls: "orbit-dismissed-drawer" });
    const toggleBtn = drawer.createEl("a", {
      cls: "orbit-dismissed-toggle",
      text: `${this.showDismissed ? "\u25BE Hide" : "\u25B8 Show"} ${noteDismissed.length} dismissed`
    });
    toggleBtn.onclick = () => {
      this.showDismissed = !this.showDismissed;
      this.render();
    };
    if (this.showDismissed) {
      const listEl = drawer.createDiv({ cls: "orbit-dismissed-list" });
      for (const [key, item] of noteDismissed) {
        const row = listEl.createDiv({ cls: "orbit-dismissed-row" });
        row.createSpan({ cls: "orbit-dismissed-title", text: item.targetTitle || item.targetPath });
        const restoreBtn = row.createEl("button", { cls: "orbit-btn-sm", text: "Restore" });
        restoreBtn.onclick = async () => {
          delete this.plugin.settings.dismissedSuggestions[key];
          await this.plugin.saveSettings();
          this.render();
        };
      }
    }
  }
  renderInferencesSection(container) {
    const infs = this.context?.inferred_relationships || [];
    const sec = container.createDiv({ cls: "orbit-section" });
    sec.createDiv({
      cls: "orbit-section-header",
      text: `Inferred Relationships (${infs.length})`
    });
    if (infs.length === 0) {
      sec.createDiv({ cls: "orbit-empty-state", text: "No AI inferences for this note." });
      return;
    }
    for (const rel of infs) {
      const isContra = rel.rel_type === "CONTRADICTS";
      const card = sec.createDiv({
        cls: `orbit-card ${isContra ? "orbit-card-contradiction" : ""}`
      });
      const cardHead = card.createDiv({ cls: "orbit-card-header" });
      const targetTitle = rel.target_path.replace(/\.md$/, "");
      const link = cardHead.createEl("a", { cls: "orbit-card-target", text: targetTitle });
      link.onclick = () => this.app.workspace.openLinkText(rel.target_path, "");
      const badgeCls = isContra ? "orbit-badge orbit-badge-warning" : "orbit-badge orbit-badge-accent";
      cardHead.createSpan({ cls: badgeCls, text: rel.rel_type });
      if (rel.reason) {
        card.createDiv({ cls: "orbit-card-reason", text: `"${rel.reason}"` });
      }
    }
  }
  renderContextSection(container) {
    const sec = container.createDiv({ cls: "orbit-section" });
    sec.createDiv({ cls: "orbit-section-header", text: "Graph Context" });
    const tags = this.context?.tags || [];
    if (tags.length > 0) {
      const tagChips = sec.createDiv({ cls: "orbit-chip-container", attr: { style: "margin-bottom: 8px;" } });
      for (const t of tags) {
        tagChips.createSpan({ cls: "orbit-chip", text: `#${t}` });
      }
    }
    const backlinks = this.context?.backlinks || [];
    sec.createDiv({
      cls: "orbit-card-reason",
      text: `Backlinks: ${backlinks.length}  |  Outgoing: ${this.context?.outgoing_links?.length || 0}  |  2-Hop Cluster: ${this.context?.neighbors_2hop?.length || 0}`
    });
  }
};

// src/main.ts
var OrbitInsightsPlugin = class extends import_obsidian4.Plugin {
  settings = DEFAULT_SETTINGS;
  client;
  statusBarEl;
  eventSource = null;
  debounceMap = /* @__PURE__ */ new Map();
  activeInsights = /* @__PURE__ */ new Map();
  async onload() {
    await this.loadSettings();
    this.client = new OrbitClient(this.settings);
    if (!this.settings.authToken) {
      await this.client.autoDiscoverVaultToken(this.app);
    }
    (0, import_obsidian4.addIcon)(
      "pkmrag-ribbon",
      `<circle cx="50" cy="22" r="10" fill="none" stroke="currentColor" stroke-width="8"/><circle cx="22" cy="78" r="10" fill="none" stroke="currentColor" stroke-width="8"/><circle cx="78" cy="78" r="10" fill="none" stroke="currentColor" stroke-width="8"/><line x1="44" y1="34" x2="28" y2="66" stroke="currentColor" stroke-width="8" stroke-linecap="round"/><line x1="34" y1="78" x2="66" y2="78" stroke="currentColor" stroke-width="8" stroke-linecap="round"/><line x1="56" y1="34" x2="72" y2="66" stroke="currentColor" stroke-width="8" stroke-dasharray="4 6" stroke-linecap="round"/>`
    );
    this.registerView(
      VIEW_TYPE_ORBIT_INSIGHTS,
      (leaf) => new OrbitInsightsView(leaf, this)
    );
    this.addRibbonIcon("pkmrag-ribbon", "PKMRAG Insights", () => {
      this.activateView();
    });
    this.statusBarEl = this.addStatusBarItem();
    this.updateStatusBar(false);
    this.checkConnection();
    this.addCommand({
      id: "open-orbit-insights",
      name: "Open Insights Sidebar",
      callback: () => this.activateView()
    });
    this.addCommand({
      id: "refresh-orbit-insights",
      name: "Refresh Insights for Active Note",
      callback: () => this.refreshActiveView()
    });
    this.registerEditorExtension(createOrbitEditorExtension(this));
    this.addCommand({
      id: "sync-orbit-vault",
      name: "Sync Vault Index (Incremental)",
      callback: async () => {
        new import_obsidian4.Notice("PKMRAG: Synchronizing vault delta...");
        try {
          const results = await this.client.syncVault();
          new import_obsidian4.Notice(`PKMRAG: Synchronized ${results.length} notes.`);
        } catch (err) {
          const msg = err instanceof Error ? err.message : String(err);
          new import_obsidian4.Notice(`PKMRAG Sync Failed: ${msg}`);
        }
      }
    });
    this.addCommand({
      id: "toggle-orbit-inline-indicators",
      name: "Toggle Inline Heading Indicators",
      callback: async () => {
        this.settings.showInlineIndicators = !this.settings.showInlineIndicators;
        await this.saveSettings();
        new import_obsidian4.Notice(
          `PKMRAG: Inline indicators ${this.settings.showInlineIndicators ? "enabled" : "disabled"}`
        );
        this.app.workspace.updateOptions();
      }
    });
    this.addCommand({
      id: "clear-orbit-dismissed",
      name: "Clear Dismissed Suggestions",
      callback: async () => {
        this.settings.dismissedSuggestions = {};
        await this.saveSettings();
        new import_obsidian4.Notice("PKMRAG: Cleared all dismissed suggestions.");
        this.refreshActiveView();
      }
    });
    this.registerEvent(
      this.app.vault.on("modify", (file) => {
        if (!this.settings.autoSyncOnSave || !(file instanceof import_obsidian4.TFile) || file.extension !== "md") {
          return;
        }
        const timer = this.debounceMap.get(file.path);
        if (timer) window.clearTimeout(timer);
        const newTimer = window.setTimeout(async () => {
          this.debounceMap.delete(file.path);
          try {
            await this.client.reindexNote(file.path);
          } catch (err) {
            console.warn(`[Orbit] Reindex failed for ${file.path}:`, err);
          }
        }, 1500);
        this.debounceMap.set(file.path, newTimer);
      })
    );
    this.registerEvent(
      this.app.workspace.on("file-open", (file) => {
        if (!this.settings.autoRefreshOnNoteOpen || !file || file.extension !== "md") {
          return;
        }
        this.refreshActiveView(file.path);
      })
    );
    this.addSettingTab(new OrbitSettingTab(this.app, this));
    this.initEventStream();
  }
  onunload() {
    if (this.eventSource) {
      this.eventSource.close();
      this.eventSource = null;
    }
    for (const timer of this.debounceMap.values()) {
      window.clearTimeout(timer);
    }
    this.debounceMap.clear();
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
    this.client.settings = this.settings;
    this.checkConnection();
    this.initEventStream();
  }
  async activateView() {
    const { workspace } = this.app;
    let leaf = null;
    const leaves = workspace.getLeavesOfType(VIEW_TYPE_ORBIT_INSIGHTS);
    if (leaves.length > 0) {
      leaf = leaves[0];
    } else {
      leaf = workspace.getRightLeaf(false);
      if (leaf) {
        await leaf.setViewState({ type: VIEW_TYPE_ORBIT_INSIGHTS, active: true });
      }
    }
    if (leaf) {
      workspace.revealLeaf(leaf);
      const activeFile = workspace.getActiveFile();
      if (activeFile && activeFile.extension === "md") {
        const view = leaf.view;
        await view.loadInsightsForNote(activeFile.path);
      }
    }
  }
  refreshActiveView(notePath) {
    const leaves = this.app.workspace.getLeavesOfType(VIEW_TYPE_ORBIT_INSIGHTS);
    if (leaves.length === 0) return;
    const view = leaves[0].view;
    const path = notePath || this.app.workspace.getActiveFile()?.path;
    if (path) {
      view.loadInsightsForNote(path);
    }
  }
  insertLink(targetTitle) {
    const view = this.app.workspace.getActiveViewOfType(import_obsidian4.MarkdownView);
    if (!view || !view.editor) {
      new import_obsidian4.Notice(`No active markdown editor to insert [[${targetTitle}]].`);
      return;
    }
    const editor = view.editor;
    const wikilink = `[[${targetTitle}]]`;
    editor.replaceSelection(wikilink);
    new import_obsidian4.Notice(`Inserted link to ${wikilink}`);
  }
  setActiveInsights(path, gaps, inferences) {
    const dismissed = this.settings.dismissedSuggestions || {};
    const visibleCount = gaps.filter(
      (g) => !dismissed[`${g.source_path}::${g.target_path}`]
    ).length;
    const hasContra = inferences.some((i) => i.rel_type === "CONTRADICTS");
    this.activeInsights.set(path, { gapsCount: visibleCount, hasContradiction: hasContra });
    this.app.workspace.updateOptions();
  }
  getActiveGapsCount(path) {
    return this.activeInsights.get(path)?.gapsCount || 0;
  }
  hasActiveContradiction(path) {
    return this.activeInsights.get(path)?.hasContradiction || false;
  }
  async checkConnection() {
    try {
      await this.client.checkHealth();
      this.updateStatusBar(true);
    } catch {
      this.updateStatusBar(false);
    }
  }
  updateStatusBar(connected) {
    if (!this.statusBarEl) return;
    this.statusBarEl.empty();
    const text = connected ? "PKMRAG: Connected" : "PKMRAG: Offline";
    this.statusBarEl.createSpan({
      text,
      cls: connected ? "orbit-status-connected" : "orbit-status-disconnected"
    });
    this.statusBarEl.onclick = () => this.activateView();
  }
  initEventStream() {
    if (this.eventSource) {
      this.eventSource.close();
      this.eventSource = null;
    }
    this.eventSource = this.client.connectEvents((event, data) => {
      const activeFile = this.app.workspace.getActiveFile();
      if (!activeFile) return;
      if (event === "reindex") {
        const reindexed = data.note_path;
        if (reindexed && activeFile.path.endsWith(reindexed)) {
          this.refreshActiveView(activeFile.path);
        }
      } else if (event === "sync") {
        this.refreshActiveView(activeFile.path);
      }
    });
  }
};
